[[mounts]]
  source = "node_modules/@hyas/core/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@hyas/core/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/seo/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/images/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/themes-doks/archetypes"
  target = "archetypes"

[[mounts]]
  source = "node_modules/@hyas/themes-doks/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@hyas/themes-doks/data"
  target = "data"

[[mounts]]
  source = "node_modules/@hyas/themes-doks/i18n"
  target = "i18n"

[[mounts]]
  source = "node_modules/@hyas/themes-doks/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/themes-doks/static"
  target = "static"

[[mounts]]
  source = "node_modules/flexsearch"
  target = "assets/js/vendor/flexsearch"

[[mounts]]
  source = "node_modules/katex"
  target = "assets/js/vendor/katex"

[[mounts]]
  source = "node_modules/mermaid"
  target = "assets/js/vendor/mermaid"

[[mounts]]
  source = "archetypes"
  target = "archetypes"

[[mounts]]
  source = "assets"
  target = "assets"

[[mounts]]
  source = "data"
  target = "data"

[[mounts]]
  source = "i18n"
  target = "i18n"

[[mounts]]
  source = "layouts"
  target = "layouts"

[[mounts]]
  source = "static"
  target = "static"